kind: pipeline
type: docker
name: test-and-notify

node:
  type: tuya-ci

volumes:
  - name: node-cache
    host:
      path: /home/docker/workspace/cache/.node_cache

steps:
  - name: test
    image: registry.shdocker.tuya-inc.top/fe-base/compile/node:14.4.0
    volumes:
      - name: node-cache
        path: /usr/local/share/.cache/yarn
    commands:
      - yarn install --frozen-lockfile --silent
      - yarn test
    when:
      branch:
        - master
        - develop_1.0.x
      event:
        - push
        - pull_request

  # - name: notify-wx
  #   image: registry.shdocker.tuya-inc.top/fe-base/compile/node:14.4.0
  #   volumes:
  #     - name: node-cache
  #       path: /usr/local/share/.cache/yarn
  #   commands:
  #     - echo 'Start notify wx'
  #     - node scripts/notify.js
  #   when:
  #     event:
  #       - tag
