kind: pipeline
type: docker
name: Sync TYNativeApi

node:
  type: tuya-ci

volumes:
  - name: node-cache
    host:
      path: /home/docker/workspace/cache/.node_cache

steps:
  - name: synchronize
    image: registry.shdocker.tuya-inc.top/fe-base/compile/node:14.4.0
    volumes:
      - name: node-cache
        path: /usr/local/share/.cache/yarn
    commands:
      - bash sync.sh
    when:
      branch:
        - TYNativeApi
      event:
        - push