export const MOCK_ORIG_DEV_INFO = {
  ability: 0,
  activeTime: 1601448061,
  appId: 168,
  appKey: 'nfdmss3jjw4jtydrnmhn',
  attribute: 348429221892,
  baseAttribute: 1024,
  bv: 2,
  capability: 1,
  category: 'cz',
  categoryCode: 'wf_cz',
  cloudOnline: true,
  communication: {
    communicationNode: 'vdevo160144806173311',
    communicationModes: [
      {
        type: 1,
        pv: 2,
      },
    ],
  },
  devAttribute: 0,
  devId: 'vdevo160144806173311',
  deviceType: 0,
  displayDps: [],
  displayMsgs: {
    quickop_dp_countdown: '倒计时',
    quickop_dp_countdown_5: '开关5倒计时',
    quickop_dp_countdown_usb2_unit: 's',
    quickop_dp_countdown_left: '倒计时剩余时间',
    quickop_dp_countdown_6: '开关6倒计时',
    quickop_dp_countdown_usb4: 'USB4倒计时',
    quickop_dp_switch_1: '开关',
    quickop_dp_countdown_usb4_unit: 's',
    quickop_dp_switch_1_off: '关闭',
    quickop_dp_countdown_3_unit: 's',
    quickop_dp_countdown_usb3: 'USB3倒计时',
    quickop_dp_countdown_0: '取消',
    quickop_dp_countdown_led_unit: 's',
    quickop_dp_countdown_1: '开关1倒计时',
    quickop_dp_countdown_4_unit: 's',
    quickop_dp_countdown_usb2: 'USB2倒计时',
    quickop_dp_countdown_1_unit: 's',
    quickop_dp_countdown_usb3_unit: 's',
    quickop_dp_countdown_2: '开关2倒计时',
    quickop_dp_countdown_unit: 'm',
    quickop_dp_countdown_usb1_unit: 's',
    quickop_dp_countdown_3: '开关3倒计时',
    quickop_dp_countdown_6_unit: 's',
    quickop_dp_countdown_usb1: 'USB1倒计时',
    quickop_dp_countdown_5_unit: 's',
    quickop_dp_countdown_4: '开关4倒计时',
    quickop_dp_countdown_2_unit: 's',
    quickop_dp_countdown_led: '情景灯倒计时',
    quickop_dp_switch_1_on: '开启',
  },
  displayOrder: -1,
  dpMaxTime: 1601448061758,
  dpName: {},
  dps: {
    '1': false,
    '11': 0,
  },
  errorCode: 0,
  faultDps: [],
  gatewayVerCAD: '',
  gwType: 'v',
  homeDisplayOrder: 60,
  homeId: 2097530,
  i18nTime: 1600856565876,
  iconUrl:
    'https://airtake-public-data-1254153901.cos.ap-shanghai.myqcloud.com/smart/product_icon/cz.png',
  ip: '',
  isAdmin: true,
  isCloudOnline: true,
  isLocalOnline: false,
  isMeshBleOnline: false,
  isNewFirmware: false,
  isOnline: true,
  isShare: false,
  isUniversalPanel: false,
  isVDevice: false,
  latitude: '',
  localKey: '1a493957e0ea503a',
  longitude: '',
  lpv: 0,
  meshId: 'me6c17ccfefd318d8909o6',
  name: '羽佳测试插座-vdevo',
  networkType: 'WIFI',
  originJson: {
    cloudOnline: true,
    lon: '',
    activeTime: 1601448061,
    id: '1Cfvy0yUtbpTD3dD',
    category: 'cz',
    shortcut: {
      quickOpDps: [1, 11],
      displayMsgs: {
        quickop_dp_countdown: '倒计时',
        quickop_dp_countdown_5: '开关5倒计时',
        quickop_dp_countdown_usb2_unit: 's',
        quickop_dp_countdown_left: '倒计时剩余时间',
        quickop_dp_countdown_6: '开关6倒计时',
        quickop_dp_countdown_usb4: 'USB4倒计时',
        quickop_dp_switch_1: '开关',
        quickop_dp_countdown_usb4_unit: 's',
        quickop_dp_switch_1_off: '关闭',
        quickop_dp_countdown_3_unit: 's',
        quickop_dp_countdown_usb3: 'USB3倒计时',
        quickop_dp_countdown_0: '取消',
        quickop_dp_countdown_led_unit: 's',
        quickop_dp_countdown_1: '开关1倒计时',
        quickop_dp_countdown_4_unit: 's',
        quickop_dp_countdown_usb2: 'USB2倒计时',
        quickop_dp_countdown_1_unit: 's',
        quickop_dp_countdown_usb3_unit: 's',
        quickop_dp_countdown_2: '开关2倒计时',
        quickop_dp_countdown_unit: 'm',
        quickop_dp_countdown_usb1_unit: 's',
        quickop_dp_countdown_3: '开关3倒计时',
        quickop_dp_countdown_6_unit: 's',
        quickop_dp_countdown_usb1: 'USB1倒计时',
        quickop_dp_countdown_5_unit: 's',
        quickop_dp_countdown_4: '开关4倒计时',
        quickop_dp_countdown_2_unit: 's',
        quickop_dp_countdown_led: '情景灯倒计时',
        quickop_dp_switch_1_on: '开启',
      },
      faultDps: [],
      displayDps: [],
    },
    capability: 1,
    communication: {
      communicationNode: 'vdevo160144806173311',
      communicationModes: [
        {
          type: 1,
          pv: '2.0',
        },
      ],
      connectionStatus: 1,
    },
    supportGroup: true,
    attribute: 348429221892,
    baseAttribute: 1024,
    devAttribute: 0,
    virtual: true,
    standard: false,
    uuid: 'vdevo160144806173311',
    ownerId: '2097530',
    localKey: '1a493957e0ea503a',
    devId: 'vdevo160144806173311',
    meshCategory: '',
    name: '羽佳测试插座-vdevo',
    dataPointInfo: {
      dpName: {},
      dpsTime: {
        '1': 1601448061758,
        '11': 1601448061758,
      },
      dps: {
        '1': false,
        '11': 0,
      },
      dpMaxTime: 1601448061758,
    },
    i18nTime: 1600856565876,
    timezoneId: 'Asia/Shanghai',
    supportSGroup: false,
    sSchema: {
      statusSchemaList: [],
      functionSchemaList: [],
    },
    panelConfig: {
      bic: [
        {
          selected: true,
          code: 'timer',
        },
        {
          selected: true,
          code: 'jump_url',
        },
      ],
      layout: {
        version: '1.0.0',
        timestamp: '1562222293377',
        theme: 'orange',
        layout: [
          {
            code: 'switch_1',
            icon: 'icon-dp_power2',
            element: 'LARGE',
            background: 'https://images.tuyacn.com/smart/theme-background/00.jpg',
          },
          {
            element: 'SMALL',
            icon: 'icon-dp_power2',
            code: 'switch_2',
          },
          {
            element: 'SMALL',
            icon: 'icon-dp_power2',
            code: 'switch_3',
          },
          {
            element: 'SMALL',
            icon: 'icon-dp_power2',
            code: 'switch_4',
          },
          {
            element: 'MIDDLE',
            icon: 'icon-dp_power2',
            code: 'switch_5',
          },
          {
            element: 'MIDDLE',
            icon: 'icon-dp_power2',
            code: 'switch_6',
          },
          {
            element: 'MIDDLE',
            icon: 'icon-dp_power',
            code: 'switch_usb1',
          },
          {
            element: 'MIDDLE',
            icon: 'icon-dp_power',
            code: 'switch_usb2',
          },
          {
            element: 'MIDDLE',
            icon: 'icon-dp_power',
            code: 'switch_usb3',
          },
          {
            element: 'MIDDLE',
            icon: 'icon-dp_power',
            code: 'switch_usb4',
          },
          {
            element: 'MIDDLE',
            icon: 'icon-dp_time2',
            code: 'countdown',
          },
          {
            element: 'POWER',
            code: 'switch_1',
          },
        ],
      },
    },
    iconUrl:
      'https://airtake-public-data-1254153901.cos.ap-shanghai.myqcloud.com/smart/product_icon/cz.png',
    runtimeEnv: 'prod',
    lat: '',
    uiInfo: {
      phase: 'release',
      id: 712359,
      ui: '00000001oi_1.2.1',
      type: 'RN',
      rnFind: true,
      appRnVersion: '5.1',
    },
    gatewayVerCAD: '',
    schemaInfo: {
      schemaExt:
        '[{"complexType":"plain","id":1,"inputStyle":"","inputType":"plain"},{"complexType":"","id":11,"inputStyle":"","inputType":"plain"}]',
      schema:
        '[{"mode":"rw","code":"switch_1","name":"单插开关","property":{"type":"bool"},"iconname":"icon-dp_power2","id":1,"type":"obj"},{"mode":"rw","code":"countdown","name":"倒计时剩余时间","property":{"unit":"秒","min":0,"max":3600,"scale":0,"step":2,"type":"value"},"iconname":"icon-dp_time2","id":11,"type":"obj"}]',
    },
    otaInfo: {
      supportAuto: true,
      otaModuleMap: {
        mcu: {
          cdv: '',
          upgradeStatus: 0,
          verSw: '1.0.0',
        },
        wifi: {
          upgradeStatus: 0,
          bv: '2.0',
          cdv: '',
          verSw: '1.0.0',
        },
      },
      otaUpgradeModes: [0],
    },
    ip: '',
    categoryCode: 'wf_cz',
    productId: '1Cfvy0yUtbpTD3dD',
  },
  panelConfig: {
    bic: [
      {
        selected: true,
        code: 'timer',
      },
      {
        selected: true,
        code: 'jump_url',
      },
    ],
    layout: {
      layout: [
        {
          code: 'switch_1',
          icon: 'icon-dp_power2',
          element: 'LARGE',
          background: 'https://images.tuyacn.com/smart/theme-background/00.jpg',
        },
        {
          element: 'SMALL',
          icon: 'icon-dp_power2',
          code: 'switch_2',
        },
        {
          element: 'SMALL',
          icon: 'icon-dp_power2',
          code: 'switch_3',
        },
        {
          element: 'SMALL',
          icon: 'icon-dp_power2',
          code: 'switch_4',
        },
        {
          element: 'MIDDLE',
          icon: 'icon-dp_power2',
          code: 'switch_5',
        },
        {
          element: 'MIDDLE',
          icon: 'icon-dp_power2',
          code: 'switch_6',
        },
        {
          element: 'MIDDLE',
          icon: 'icon-dp_power',
          code: 'switch_usb1',
        },
        {
          element: 'MIDDLE',
          icon: 'icon-dp_power',
          code: 'switch_usb2',
        },
        {
          element: 'MIDDLE',
          icon: 'icon-dp_power',
          code: 'switch_usb3',
        },
        {
          element: 'MIDDLE',
          icon: 'icon-dp_power',
          code: 'switch_usb4',
        },
        {
          element: 'MIDDLE',
          icon: 'icon-dp_time2',
          code: 'countdown',
        },
        {
          element: 'POWER',
          code: 'switch_1',
        },
      ],
      timestamp: '1562222293377',
      theme: 'orange',
      version: '1.0.0',
    },
  },
  pcc: '',
  productId: '1Cfvy0yUtbpTD3dD',
  protocolAttribute: 0,
  pv: 2,
  quickOpDps: [1, 11],
  rnFind: true,
  roomId: 0,
  runtimeEnv: 'prod',
  schema:
    '[{"mode":"rw","code":"switch_1","name":"单插开关","property":{"type":"bool"},"iconname":"icon-dp_power2","id":1,"type":"obj"},{"mode":"rw","code":"countdown","name":"倒计时剩余时间","property":{"unit":"秒","min":0,"max":3600,"scale":0,"step":2,"type":"value"},"iconname":"icon-dp_time2","id":11,"type":"obj"}]',
  schemaExt:
    '[{"complexType":"plain","id":1,"inputStyle":"","inputType":"plain"},{"complexType":"","id":11,"inputStyle":"","inputType":"plain"}]',
  sharedTime: 0,
  sigmeshId: 'me6ca14780a9271e9c0fim',
  standSchemaModel: {
    statusSchemaList: [],
    functionSchemaList: [],
    isProductCompatibled: false,
  },
  standard: false,
  supportGroup: true,
  supportSGroup: false,
  timezoneId: 'Asia/Shanghai',
  ui: '00000001oi_1.2.1',
  uiId: '00000001oi',
  uiPhase: 'release',
  uiType: 'RN',
  uiVersion: '1.2.1',
  upgrading: false,
  uuid: 'vdevo160144806173311',
  vendorInfo: '',
  verSw: '1.0.0',
  virtual: true,
};

// eslint-disable-next-line no-unused-vars
const { isOnline, ...origDevInfo } = MOCK_ORIG_DEV_INFO;

// 转换过后的 devInfo
export const MOCK_TRANS_DEV_INFO = {
  ...origDevInfo,
  appOnline: true,
  codeIds: {
    countdown: '11',
    switch_1: '1',
  },
  deviceOnline: true,
  idCodes: {
    '1': 'switch_1',
    '11': 'countdown',
  },
  isVDevice: true,
  schema: {
    countdown: {
      code: 'countdown',
      dptype: 'obj',
      iconname: 'icon-dp_time2',
      id: '11',
      max: 3600,
      min: 0,
      mode: 'rw',
      name: '倒计时剩余时间',
      scale: 0,
      step: 2,
      type: 'value',
      unit: '秒',
    },
    switch_1: {
      code: 'switch_1',
      dptype: 'obj',
      iconname: 'icon-dp_power2',
      id: '1',
      mode: 'rw',
      name: '单插开关',
      type: 'bool',
    },
  },
  state: {
    countdown: 0,
    switch_1: false,
  },
};

export const MOCK_NATIVE_MODULES = {
  TYRCTPanelManager: {
    activeSubDeviceWithGwId: jest.fn(),
    addDeviceToRoom: jest.fn(),
    addListener: jest.fn(),
    aes128DecryptedStringWithPassword: jest.fn(),
    aes128EncryptedStringWithPassword: jest.fn(),
    apiRNRequest: jest.fn(),
    apiRequest: jest.fn(),
    calculateWhiteModeColor: jest.fn(),
    calculationDistance: jest.fn(),
    checkUpdate: jest.fn(),
    deleteDeviceInfo: jest.fn().mockImplementation(resolve => resolve(true)),
    disablePopGesture: jest.fn(),
    enablePopGesture: jest.fn(),
    evilTransform: jest.fn(),
    gcj02ToWgs84Location: jest.fn(),
    getBleManagerState: jest.fn().mockImplementation(resolve => resolve({ state: true })),
    getBleRssi: jest.fn(),
    getDevInfo: jest.fn(),
    getDevProperty: jest.fn(),
    getDeviceList: jest.fn(),
    getDpDataFromClient: jest.fn(),
    getDpDataFromDevice: jest.fn(),
    getDpDataFromMeshDevice: jest.fn(),
    getDpsWithDevId: jest.fn(),
    getMeshDeviceInfoByNodeId: jest.fn(),
    getPanelInfo: jest.fn(),
    getPlayStatus: jest.fn(),
    getRoomsInCurrentHome: jest.fn(),
    getSubDeviceList: jest.fn(),
    goToAlarmListActivity: jest.fn(),
    gotoBlePermissions: jest.fn(),
    gotoDeviceWifiNetworkMonitor: jest.fn(),
    gotoDpAlarm: jest.fn(),
    postBleChannelCommand: jest.fn(),
    pushToNextPageWithDeviceId: jest.fn(),
    putDpData: jest.fn(),
    putLocalDpData: jest.fn(),
    putMqttDpData: jest.fn(),
    removeDevice: jest.fn(),
    removeGW: jest.fn(),
    removeListeners: jest.fn(),
    removeSubDevice: jest.fn(),
    renameSubDeviceName: jest.fn(),
    renameTitle: jest.fn(),
    setDevProperty: jest.fn(),
    showDeviceMenu: jest.fn(),
    startBLEListening: jest.fn(),
    stopActiveSubDeviceWithGwId: jest.fn(),
    updateLocation: jest.fn(),
  },
  TYRCTPublicManager: {
    addListener: jest.fn(),
    back: jest.fn(),
    battery: jest.fn(),
    bottomListDialog: jest.fn(),
    deviceIsCharging: jest.fn(),
    getCurrentscreenBrightness: jest.fn(),
    getMobileInfo: jest.fn(),
    getNetType: jest.fn(),
    getNetworkType: jest.fn(),
    getWiFiSsid: jest.fn(),
    hideLoading: jest.fn(),
    is24Hour: jest.fn(),
    jumpTo: jest.fn(),
    lang: {
      'zh-hans': {
        back: '返回',
      },
      zh: {
        back: '返回',
      },
      en: {
        back: 'Back',
      },
    },
    mobileInfo: {
      osSystem: '12.0',
      appVersion: '3.20.1',
      t: 1601776828.60919,
      lang: 'zh-Hans',
      service: 'AY',
      timezoneId: 'Asia/Shanghai',
      ele: '-100',
      iconfontNameMap:
        '{"icon-dp_add":"e600","icon-dp_reduce":"e601","icon-dp_temp":"e602","icon-dp_time3":"e603","icon-dp_mode":"e604","icon-dp_loop":"e605","icon-dp_filter":"e606","icon-dp_smile":"e607","icon-dp_sleep":"e608","icon-dp_dust":"e609","icon-eco":"e60a","icon-eoc2":"e60b","icon-dp_tvoc":"e60c","icon-dp_smart":"e60d","icon-dp_o2":"e60e","icon-dp_time2":"e60f","icon-dp_light2":"e610","icon-dp_shake":"e611","icon-dp_home2":"e612","icon-dp_direction":"e613","icon-dp_power3":"e614","icon-dp_wash":"e615","icon-dp_location":"e616","icon-dp_battery":"e617","icon-dp_wind":"e618","icon-dp_fresh":"e619","icon-dp_wet2":"e61a","icon-dp_half":"e61b","icon-dp_sun":"e61c","icon-dp_bag":"e61d","icon-dp_wet":"e61e","icon-dp_water":"e61f","icon-dp_lock":"e620","icon-dp_time":"e621","icon-dp_light":"e622","icon-dp_0":"e623","icon-dp_1":"e624","icon-dp_2":"e625","icon-dp_3":"e626","icon-dp_4":"e627","icon-dp_5":"e628","icon-dp_6":"e629","icon-dp_7":"e62a","icon-dp_8":"e62b","icon-dp_9":"e62c","icon-dp_c":"e62d","icon-dp_f":"e62e","icon-dp_power2":"e62f","icon-dp_power":"e630","icon-dp_right":"e631","icon-dp_dot":"e632","icon-dp_play":"e633","icon-dp_pause":"e634","icon-dp_down":"e635","icon-dp_anti-clockwise":"e636","icon-dp_clockwise":"e637","icon-dp_up":"e638","icon-dp_lightning":"e63a","icon-dp_voice":"e639","icon-dp_down1":"e63b","icon-dp_cloud":"e63c","icon-dp_upload":"e63d","icon-dp_doc":"e63e","icon-dp_curve":"e63f","icon-dp_heart":"e640","icon-dp_email":"e641","icon-dp_circle":"e642","icon-dp_plus":"e643","icon-dp_home":"e644","icon-dp_magnifier":"e645","icon-dp_fly":"e646","icon-dp_i":"e647","icon-dp_down2":"e648","icon-dp_book":"e649","icon-dp_rabbish":"e64a","icon-dp_hill":"e64b","icon-dp_compass":"e64c","icon-dp_gift":"e64d","icon-dp_eye":"e64e","icon-dp_notice":"e64f","icon-dp_camera":"e650","icon-dp_puzzle":"e651","icon-dp_ratio":"e652","icon-dp_block":"e653","icon-dp_chat":"e654","icon-dp_list2":"e655","icon-dp_bottle":"e656","icon-dp_doc2":"e657","icon-dp_what":"e658","icon-dp_warming":"e659","icon-dp_updown":"e65a","icon-dp_tool":"e65b","icon-dp_tag":"e65c","icon-dp_shield":"e65d","icon-dp_box2":"e65e","icon-dp_box":"e65f","icon-dp_money":"e660","icon-dp_house":"e661","icon-dp_mic":"e662","icon-dp_calendar":"e663","icon-dp_list":"e664","icon-dp_flag":"e665","icon-dp_flower":"e666","icon-baifeng":"e8c1","icon-chushi":"e8c2","icon-chengzhong":"e8c3","icon-chongnai":"e8c4","icon-chushi1":"e8c5","icon-chushi2":"e8c6","icon-cuowu":"e8c7","icon-deng":"e8c8","icon-dianliang":"e8c9","icon-fengli":"e8ca","icon-geren":"e8cb","icon-gaodiyin":"e8cc","icon-gongneng":"e8cd","icon-guanjia":"e8ce","icon-huoyan":"e8cf","icon-qita":"e8d0","icon-jiare":"e8d1","icon-liangdu":"e8d2","icon-jiare1":"e8d3","icon-shangsheng":"e8d4","icon-shouji":"e8d5","icon-shoucang":"e8d6","icon-shezhi":"e8d7","icon-qiangli":"e8d8","icon-tianjia":"e8d9","icon-shoushimima":"e8da","icon-shenghua":"e8db","icon-shuibeng":"e8dc","icon-tongji":"e8dd","icon-tongji1":"e8de","icon-yinshui":"e8df","icon-yinliang":"e8e0","icon-yanse":"e8e1","icon-wendu":"e8e2","icon-yundong":"e8e3","icon-yunhang":"e8e4","icon-zanting":"e8e5","icon-zhengque":"e8e6","icon-zhuangtai":"e8e7","icon-zhileng":"e8e8","icon-zhileng1":"e8e9","icon-chushuang":"e8ea","icon-zanting1":"e8eb","icon-tongji2":"e8ec","icon-baifeng1":"e8ed","icon-set":"e931","icon-yueliang":"e932","icon-xue":"e933","icon-fangzi":"e934","icon-wendu1":"e935","icon-taiyang":"e936","icon-fangzi1":"e937","icon-icon-percent":"e938","icon-p6":"e9aa","icon-p7":"e9ab","icon-p8":"e9ac","icon-p9":"e9ad","icon-p10":"e9ae","icon-p11":"e9af","icon-p12":"e9b0","icon-p13":"e9b1","icon-p14":"e9b2","icon-p15":"e9b3","icon-ziyouchengxu":"e9b4","icon-zhouchengxu":"e9b5","icon-minus":"e9ba","icon-plus":"e9bb","icon-a_fan_low":"e9bd","icon-a_fan_auto":"e9be","icon-a_fan_med":"e9bf","icon-a_fan_high":"e9c0","icon-a_function_celsius":"e9c1","icon-a_function_fahrenhei":"e9c2","icon-a_function_hs":"e9c3","icon-a_function_eco":"e9c4","icon-a_function_filter":"e9c5","icon-a_function_sleep":"e9c6","icon-a_function_pump":"e9c7","icon-a_function_vs":"e9c8","icon-a_function_turbo":"e9c9","icon-a_mode_basement":"e9ca","icon-a_mode_continuous":"e9cb","icon-a_mode_cool":"e9cc","icon-a_mode_fan":"e9cd","icon-a_mode_clothes":"e9ce","icon-a_mode_feel":"e9cf","icon-a_mode_heat":"e9d0","icon-a_mode_livingroom":"e9d1","icon-a_mode_dry":"e9d2","icon-a_nav_fan":"e9d3","icon-a_nav_function":"e9d4","icon-a_nav_mode":"e9d5","icon-a_power":"e9d6","icon-a_mode_turbo":"e9d7","icon-a_nav_timer":"e9d8","icon-a_down":"e9d9","icon-a_up":"e9da","icon-a_water":"e9db","icon-a_selected":"e9dc","icon-Mute":"e9dd","icon-FanSpeed":"e9de","icon-Lamp":"e9df","icon-Heal":"e9e0","icon-Ele":"e9e1","icon-Strong":"e9e2","icon-dp_bag1":"e9e3","icon-off":"e9e4","icon-edit":"e9e5","icon-on":"e9e6","icon-timer":"e9e7","icon-power":"e9e8","icon-timer1":"e9ea","icon-Disarm":"e9e9","icon-SystemReady":"e9eb","icon-Arm":"e9ec","icon-HomeArm":"e9ed","icon-AwayArm":"e9ee","icon-power1":"e9ef","icon-Panic":"e9f0","icon-battery":"e9f1","icon-setting":"e9f2","icon-Trigger":"e9f3","icon-CMS":"e9f4","icon-tcl_function_eco":"ea17","icon-tcl_function_vs":"ea18","icon-tcl_mode_shoes":"ea19","icon-tcl_function_hs":"ea1a","icon-tcl_function_vs1":"ea1b","icon-tcl_function_vs2":"ea1c","icon-tcl_function_light":"ea1d","icon-tcl_function_vs3":"ea1e","icon-function_eh":"ea22","icon-air_quality":"ea23","icon-sound":"ea24","icon-icon-test6":"e819","icon-icon-test7":"e81a","icon-icon-test8":"e81c","icon-icon-test9":"e81d","icon-icon-test10":"e81e","icon-gongnuan":"e820","icon-lengnuan":"e821","icon-icon-test11":"eaa8","icon-zidong":"eaa9","icon-icon-test12":"eaaa","icon-icon-test13":"eaab","icon-xiegang":"ea96","icon-a_selected-copy":"eaac","icon-dp_play-copy":"eaad","icon-jiaquan":"eb05","icon-baojing":"eb06","icon-menci":"eb07","icon-shidu":"eb08","icon-ranqi":"eb09","icon-renxingyidong":"eb0a","icon-zhendong":"eb0b","icon-wendu2":"eb0c","icon-yanwu":"eb0d","icon-liangdu1":"eb0e","icon-pm":"eb0f","icon-voc":"eb10","icon-CH":"eb28","icon-gongneng1":"eb29","icon-CO":"eb2a","icon-yali":"eb2b","icon-Light":"eb2c","icon-CO1":"eb2d","icon-chanpin":"e87b"}',
      platform: 'Simulator',
      os: 'iOS',
      appRnVersion: '5.29',
      ttid: 'appstore',
      countryCode: 'US',
      lon: '',
      lat: '',
      celsius: 0,
      phoneCode: '86',
    },
    panelInfo: {
      isVDevice: false,
    },
    removeListeners: jest.fn(),
    screenAlwaysOn: jest.fn(),
    screenBrightness: jest.fn(),
    shareMsg: jest.fn(),
    shareToSystem: jest.fn(),
    showEditDialog: jest.fn(),
    showLoading: jest.fn(),
    simpleConfirmDialog: jest.fn(),
    simpleTipDialog: jest.fn(),
    startListening: jest.fn(),
    stopListening: jest.fn(),
  },
  TYRCTBluetoothUtilManager: {
    addListener: jest.fn(),
    getBluetoothState: jest.fn().mockImplementation(resolve => resolve({ state: 3 })),
    jumpToAppSettings: jest.fn(),
    removeListeners: jest.fn(),
  },
  TYRCTNavManager: {
    addListener: jest.fn(),
    broadcastMessage: jest.fn(),
    broadcastReceiverRegister: jest.fn(),
    pushWithDevID: jest.fn(),
    pushWithUIID: jest.fn(),
    removeListeners: jest.fn(),
  },
};
